name: ${COMPOSE_PROJECT_NAME:-webprodi}

services:
  webprodi_app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    networks:
      - shared_net
    extra_hosts:
      - "host.docker.internal:host-gateway"

  webprodi_nginx:
    image: nginx:1.27-alpine
    depends_on:
      - webprodi_app
    restart: unless-stopped
    ports:
      - "${NGINX_BIND_IP:-127.0.0.1}:${NGINX_HTTP_PORT:-8001}:80"
    volumes:
      - ./public:/var/www/html/public:ro
      - ./storage:/var/www/html/storage:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - shared_net

networks:
  shared_net:
    external: true
    name: shared_net
